version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: deno
    directory: "/"
    schedule:
      interval: monthly
    groups:
      std:
        patterns:
        - "@std/*"
